* My Personal gVim Config

** Introduction

Writing down some notes as a start to develop a purposely minimal gVim
configuration.

** Links to Resources

Sainnhe Park makes top tier color schemes for vim. https://github.com/sainnhe

Everforest https://github.com/sainnhe/everforest

Edge https://github.com/sainnhe/edge

MacVim has a built in color scheme available or you can set it to any vim color
scheme. https://macvim.org/ Color scheme is located here:
/Applications/MacVim.app/Contents/Resources/vim/runtime/colors
https://macvim.org/docs/gui_mac.txt.html#macvim-colors macvim-colorscheme MacVim
ships with a custom color scheme that is used instead of the default Vim color
scheme. The color scheme can be changed with :colorscheme macvim If you prefer a
dark background color, then type :set bg=dark after having loaded the "macvim"
color scheme.

Use the :colorscheme command if you want to use another color scheme. Note that
if you want to set syntax highlight colors manually, then you must either create
your own color scheme or add the line let macvim_skip_colorscheme=1 to your
~/.vimrc (~/.gvimrc will not work). Otherwise the "macvim" color scheme will be
loaded when the system gvimrc file is sourced and mess up your changes.

The color scheme uses the system "Highlight Color", which can be changed in the
"Appearance" pane of the System Settings. It also changes the highlight color
when a window becomes inactive.

MacVim Reference Manual https://macvim.org/docs/gui_mac.txt.html#
